name: Acme Metric
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7492415327578783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aacfe2'
    - '#c02e2f'
    - '#ffffff'
    - '#231f20'
    - '#de9394'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
