name: Acme Metric
favicon: null
layout_spectrum: 0.016558048082515597
typography_spectrum: 0.7492415327578783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8134209923446178
  lightness: 0.7508357472252101
  saturation: 0.03329315478913486
  rhythmicContrast: 0.32418278348632157
purpose: []
